//export const TEST_DISPATCH = 'TEST_DISPATCH';
//----------AUTH
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

//---------REGISTER PORTAL
export const ADD_REGISTERED_USER = 'ADD_REGISTERED_USER';
export const GET_REGISTERED_USER = 'GET_REGISTERED_USER';
export const DELETE_REGISTERED_USER = 'DELETE_REGISTERED_USER';
export const AUTH_LOADING = 'AUTH_LOADING'

//---------Q&A
export const ADD_QUESTION = 'ADD_QUESTION';
export const DISPLAY_QUESTION = 'DISPLAY_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const QUESTION_LOADING = 'QUESTION_LOADING';
export const ADD_ANSWER = 'ADD_ANSWER';

//---------EVENT
export const ADD_EVENT = 'ADD_EVENT';
export const DISPLAY_EVENT = 'DISPLAY_EVENT';
export const EVENT_LOADING = 'EVENT_LOADING'

//---------ACHIEVEMENT
export const ADD_ACHIEVEMENT = 'ADD_ACHIEVEMENT';
export const DISPLAY_ACHIEVEMENT = 'DISPLAY_ACHIEVEMENT';
export const ACHIEVEMENT_LOADING = 'ACHIEVEMENT_LOADING'